// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwtvufrzuolbiobeajpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dHZ1ZnJ6dW9sYmlvYmVhanBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzE4NTYsImV4cCI6MjA3Mjc0Nzg1Nn0.O6ujmShaACsb-HtkRsP_1gfKJYRZykRFngA6C3o268g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});